// Code generated by MockGen. DO NOT EDIT.
// Source: cloudformation.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	cloudformation "github.com/aws/aws-sdk-go-v2/service/cloudformation"
	gomock "github.com/golang/mock/gomock"
)

// MockawsCloudformationAPI is a mock of awsCloudformationAPI interface.
type MockawsCloudformationAPI struct {
	ctrl     *gomock.Controller
	recorder *MockawsCloudformationAPIMockRecorder
}

// MockawsCloudformationAPIMockRecorder is the mock recorder for MockawsCloudformationAPI.
type MockawsCloudformationAPIMockRecorder struct {
	mock *MockawsCloudformationAPI
}

// NewMockawsCloudformationAPI creates a new mock instance.
func NewMockawsCloudformationAPI(ctrl *gomock.Controller) *MockawsCloudformationAPI {
	mock := &MockawsCloudformationAPI{ctrl: ctrl}
	mock.recorder = &MockawsCloudformationAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockawsCloudformationAPI) EXPECT() *MockawsCloudformationAPIMockRecorder {
	return m.recorder
}

// DescribeStacks mocks base method.
func (m *MockawsCloudformationAPI) DescribeStacks(ctx context.Context, params *cloudformation.DescribeStacksInput, optFns ...func(*cloudformation.Options)) (*cloudformation.DescribeStacksOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeStacks", varargs...)
	ret0, _ := ret[0].(*cloudformation.DescribeStacksOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeStacks indicates an expected call of DescribeStacks.
func (mr *MockawsCloudformationAPIMockRecorder) DescribeStacks(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeStacks", reflect.TypeOf((*MockawsCloudformationAPI)(nil).DescribeStacks), varargs...)
}
